import type { BuiltInProvider } from '@/lib/types/studio';

export const BUILT_IN_PROVIDERS: BuiltInProvider[] = [
  {
    id: 'runway',
    name: 'Runway ML',
    desc: 'Gen-3 Alpha • Cinematic text-to-video & motion brush',
    icon: '🎬',
    hint: 'Get your key from Runway dashboard → API',
    purposes: ['Text-to-Video', 'Image-to-Video', 'Motion Brush'],
    modalities: ['video', 'image'],
  },
  {
    id: 'luma',
    name: 'Luma AI',
    desc: 'Dream Machine • Photorealistic motion and world models',
    icon: '🌌',
    hint: 'Create API key in Luma account settings',
    purposes: ['Text-to-Video', 'Image-to-Video'],
    modalities: ['video', 'image'],
  },
  {
    id: 'kling',
    name: 'Kling AI',
    desc: 'Kling 2.0 • High-fidelity motion and lip sync',
    icon: '🐉',
    hint: 'Available via Kling developer console',
    purposes: ['Text-to-Video', 'Image-to-Video', 'Lip Sync'],
    modalities: ['video', 'image'],
  },
  {
    id: 'pika',
    name: 'Pika Labs',
    desc: 'Pika 2.2 • Creative effects, lip sync & stylization',
    icon: '⚡',
    hint: 'Access via Pika web or Discord integration',
    purposes: ['Text-to-Video', 'Image-to-Video', 'Lip Sync', 'Effects'],
    modalities: ['video', 'image'],
  },
  {
    id: 'stability',
    name: 'Stability AI',
    desc: 'Stable Video 3 • Controllable open video diffusion',
    icon: '🔬',
    hint: 'Stability platform → API keys section',
    purposes: ['Text-to-Video', 'Image-to-Video'],
    modalities: ['video', 'image'],
  },
  {
    id: 'leonardo',
    name: 'Leonardo.AI',
    desc: 'Motion 2.0 • Character-consistent animation',
    icon: '🎨',
    hint: 'Leonardo dashboard → API & keys',
    purposes: ['Image-to-Video', 'Character Animation'],
    modalities: ['video', 'image'],
  },
  {
    id: 'replicate',
    name: 'Replicate',
    desc: 'Community video models • Run any open weights',
    icon: '🔄',
    hint: 'Create token at replicate.com/account/api-tokens',
    purposes: ['Community Models', 'Open Weights'],
    modalities: ['video', 'image', 'llm'],
  },
  {
    id: 'xai',
    name: 'xAI',
    desc: 'Grok Video • Reasoning-powered high quality generation',
    icon: '🚀',
    hint: 'xAI console → API keys (Grok Video access)',
    purposes: ['Text-to-Video', 'Reasoning Video'],
    modalities: ['video', 'llm'],
  },
  {
    id: 'together',
    name: 'Together.AI',
    desc: 'Fast inference • Open video models at scale',
    icon: '🔗',
    hint: 'Together dashboard → API keys',
    purposes: ['Open Models', 'Fast Inference'],
    modalities: ['video', 'image', 'llm'],
  },
  {
    id: 'fal',
    name: 'Fal.ai',
    desc: 'Serverless • Instant video & image-to-video APIs',
    icon: '⚡',
    hint: 'Fal dashboard → API keys',
    purposes: ['Text-to-Video', 'Image-to-Video', 'Serverless'],
    modalities: ['video', 'image'],
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    desc: 'Open video models • Inference Endpoints & Spaces',
    icon: '🤗',
    hint: 'HF settings → Access Tokens (with read/write)',
    purposes: ['Inference Endpoints', 'Open Models'],
    modalities: ['video', 'image', 'llm'],
  },
  {
    id: 'minimax',
    name: 'Minimax',
    desc: 'Hailuo Video • Cinematic motion & prompt adherence',
    icon: '🌊',
    hint: 'Minimax developer portal → API credentials',
    purposes: ['Text-to-Video', 'Cinematic Motion'],
    modalities: ['video'],
  },
  {
    id: 'viggle',
    name: 'Viggle',
    desc: 'Mix & Motion • Character animation from images',
    icon: '🕺',
    hint: 'Viggle account → API section',
    purposes: ['Motion Control', 'Character Swap'],
    modalities: ['video', 'image'],
  },
  {
    id: 'hedra',
    name: 'Hedra',
    desc: 'Expressive avatars • Talking head video with emotion',
    icon: '🎭',
    hint: 'Hedra platform → Developer API keys',
    purposes: ['Talking Head', 'Avatar', 'Lip Sync'],
    modalities: ['video', 'tts'],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    desc: 'Sora • Advanced world simulation & video',
    icon: '🔷',
    hint: 'OpenAI platform → API keys (Sora access)',
    purposes: ['World Simulation', 'Text-to-Video'],
    modalities: ['video', 'llm', 'image', 'tts'],
  },
];